spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:oauth2}?autoReconnect=true
    username: ${MYSQL_USERNAME:test_user}
    password: ${MYSQL_PASSWORD:test_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  port: 9000